# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-24 21:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('activityID', models.AutoField(primary_key=True, serialize=False)),
                ('activityName', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('superUser', models.IntegerField(blank=True)),
                ('userLimit', models.IntegerField(blank=True)),
                ('inactiveUsers', models.NullBooleanField()),
                ('revisionState', models.NullBooleanField()),
                ('allowReplayActivity', models.NullBooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ActivitySession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.DateTimeField()),
                ('inactive', models.NullBooleanField()),
                ('activityCompleted', models.NullBooleanField()),
                ('activityID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chfapp.Activity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('adminID', models.AutoField(primary_key=True, serialize=False)),
                ('organization', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdminForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=10)),
                ('last_name', models.CharField(default='', max_length=10)),
                ('username', models.CharField(default='', max_length=10)),
                ('password', models.CharField(default='', max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('organization', models.CharField(default='', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('eventID', models.AutoField(primary_key=True, serialize=False)),
                ('eventName', models.CharField(max_length=255)),
                ('joincode', models.CharField(max_length=50)),
                ('enforceUser', models.NullBooleanField()),
                ('adminID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chfapp.Admin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NextScene',
            fields=[
                ('nextSceneID', models.AutoField(primary_key=True, serialize=False)),
                ('nextSceneNumber', models.IntegerField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('sceneID', models.AutoField(primary_key=True, serialize=False)),
                ('instructionText', models.CharField(max_length=255)),
                ('sceneType', models.NullBooleanField()),
                ('allowReplayScene', models.NullBooleanField()),
                ('activityID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chfapp.Activity')),
            ],
        ),
        migrations.CreateModel(
            name='SceneOptions',
            fields=[
                ('soID', models.AutoField(primary_key=True, serialize=False)),
                ('sceneText', models.CharField(max_length=500)),
                ('sceneID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chfapp.Scene')),
            ],
        ),
        migrations.CreateModel(
            name='UserForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=10)),
                ('password', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='nextscene',
            name='sceneID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sceneNS', to='chfapp.SceneOptions'),
        ),
        migrations.AddField(
            model_name='nextscene',
            name='sceneOptionID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sceneOptionNS', to='chfapp.SceneOptions'),
        ),
        migrations.AddField(
            model_name='activity',
            name='adminID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adminOwner', to='chfapp.Admin'),
        ),
        migrations.AddField(
            model_name='activity',
            name='eventID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chfapp.Event'),
        ),
        migrations.AlterUniqueTogether(
            name='sceneoptions',
            unique_together=set([('soID', 'sceneID')]),
        ),
        migrations.AlterUniqueTogether(
            name='nextscene',
            unique_together=set([('sceneOptionID', 'sceneID')]),
        ),
        migrations.AlterUniqueTogether(
            name='activitysession',
            unique_together=set([('user', 'activityID', 'startTime')]),
        ),
    ]
